"""Render ``DESIGN.md`` — the reasoning behind a generated dashboard.

A dashboard people trust explains itself. Next to every generated project pbigen writes the
design brief: the business context it inferred, the objectives and the decisions they support,
the KPI tree with definitions, what the research stage found, the storyline page by page (with
each visual's purpose), what the critique stage changed, and any gaps the data cannot answer.

Author: Arka Gupta
"""
from __future__ import annotations

from ..core.design import Design
from ..core.schema import Schema


def _as_list(x) -> list:
    if x is None:
        return []
    return x if isinstance(x, list) else [x]


def _fmt(item) -> str:
    if isinstance(item, dict):
        head = item.get("name") or item.get("objective") or item.get("q") or item.get("question") \
            or item.get("insight") or item.get("role") or item.get("issue") or ""
        rest = [f"{k}: {v}" for k, v in item.items()
                if k not in ("name", "objective", "q", "question", "insight", "role", "issue") and v not in (None, "", [])]
        return f"**{head}**" + (f" — {'; '.join(str(r) for r in rest)}" if rest else "") if head else "; ".join(rest)
    return str(item)


def render_design_md(design: Design, schema: Schema, name: str) -> str:
    b = design.brief or {}
    out: list[str] = [f"# {name} — design brief", ""]
    out.append(f"_Generated by pbigen · engine: {b.get('engine', 'unknown')} · source table: `{schema.table}`_")
    out.append("")

    def section(title: str, items, key_fmt=_fmt) -> None:
        items = _as_list(items)
        if not items:
            return
        out.extend([f"## {title}", ""])
        for it in items:
            out.append(f"- {key_fmt(it)}")
        out.append("")

    ctx = b.get("context") if isinstance(b.get("context"), dict) else {}
    out.extend(["## Business context", ""])
    for label, val in (("Domain", b.get("domain") or ctx.get("domain")),
                       ("Business model", ctx.get("business_model")),
                       ("Grain", b.get("grain") or ctx.get("grain")),
                       ("Audience", b.get("audience") or ctx.get("audience")),
                       ("Objective", b.get("objective")),
                       ("North star", b.get("north_star"))):
        if val:
            if isinstance(val, list):
                val = "; ".join(_fmt(v) for v in val)
            elif isinstance(val, dict):
                val = _fmt(val)
            out.append(f"- **{label}:** {val}")
    out.append("")
    section("Column meanings", [f"`{k}` — {v}" for k, v in (ctx.get("column_semantics") or {}).items()])
    section("Objectives & decisions", b.get("objectives"))
    section("KPI tree", b.get("kpis"))
    research = b.get("research") if isinstance(b.get("research"), dict) else {}
    if research:
        out.extend([f"## Research ({research.get('mode', 'built-in')})", ""])
        for f in _as_list(research.get("findings")):
            out.append(f"- {_fmt(f)}")
        srcs = list(dict.fromkeys(str(s) for s in _as_list(research.get("sources"))))
        for s in srcs[:8]:
            out.append(f"- Source: {s}")
        if len(srcs) > 8:
            out.append(f"- … and {len(srcs) - 8} more sources")
        out.append("")

    out.extend(["## Storyline", ""])
    for i, p in enumerate(design.pages, 1):
        out.append(f"### {i}. {p.name}")
        if p.question:
            out.append(f"_{p.question}_")
        out.append("")
        for v in p.visuals:
            what = v.title or v.type
            binds = ", ".join(v.measures + v.line_measures)
            by = f" by `{v.category}`" if v.category else ""
            out.append(f"- **{what}** ({v.type}{by}{': ' + binds if binds else ''})"
                       + (f" — {v.subtitle}" if v.subtitle else ""))
        for head, lines in p.sections:
            out.append(f"- **{head}:** " + " · ".join(lines[:3]) + (" …" if len(lines) > 3 else ""))
        if p.slicers:
            out.append(f"- Filters: {', '.join(p.slicers)}")
        out.append("")

    section("Measures", [f"`{m.name}` — {m.description or m.kind}" for m in design.measures if not m.hidden])
    section("Design review (critique stage)", b.get("critique"))
    section("Gaps — questions this data cannot answer", b.get("gaps"))
    section("Caveats", b.get("caveats"))
    stages = _as_list(b.get("stages"))
    if stages:
        out.extend(["## Pipeline", ""])
        for s in stages:
            out.append(f"- {s.get('stage')}: {s.get('status')}" + (f" ({s.get('note')})" if s.get("note") else ""))
        out.append("")
    return "\n".join(out).rstrip() + "\n"
